version: "3.8"

networks:
  pmb-network:
    external: false

services:
  pmb-service:
    build:
      context: "."
    networks:
      - "pmb-network"
    ports:
      - 50051:${GRPC_PORT}
    depends_on:
      - "db"
    environment:
      GRPC_HOST: ${GRPC_HOST}
      GRPC_PORT: ${GRPC_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    restart: "on-failure"

  db:
    image: "postgres:15.2-alpine"
    networks:
      - "pmb-network"
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: "on-failure"

  adminer:
    image: "adminer"
    networks:
      - "playlist-network"
    restart: "on-failure"
    depends_on:
      - "db"
    ports:
      - "8080:8080"