# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build backend
      run: |
        cd backend
        go build cmd/playcount-monitor/main.go

    - name: Build tracker
      run: |
        cd backend
        go build cmd/playcount-tracker/main.go

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Unit test
      run: |
        cd backend
        go test -v -cover ./...

    - name: Integration test
      run: |
        cd backend
        export RUN_INTEGRATION_TEST=true
        go test -v -cover ./tests/...
