name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build backend
        run: |
          cd backend
          go build cmd/playcount-monitor/main.go

      - name: Build worker
        run: |
          cd backend 
          go build cmd/playcount-tracker/main.go

      - name: Unit test
        run: |
          cd backend
          go test -v -cover ./...

      - name: Integration test
        run: |
          cd backend
          export RUN_INTEGRATION_TEST=true
          go test -v -cover ./tests/...

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
